<!-- <div id="cheatsheet" class="mod box3">
	<div class="hd">
		<h4>Cheat Sheets</h4>
	</div>
	<div class="bd">
		<h5><?php echo $component;?> (.pdf)</h5>
		<a href="http://yuiblog.com/assets/pdf/cheatsheets/<?php echo $section;?>.pdf" id="pdf-single"><img src="http://us.i1.yimg.com/us.yimg.com/i/ydn/yuiweb/img/cheatsheet-images/<?php echo $section;?>.gif" alt="Image: Cheat sheet for <?php echo $component;?>"></a>
	</div>
	<div class="ft">
		<h5>Complete Set (.zip)</h5>
		<a href="/yui/docs/assets/cheatsheets.zip" class="download" id="pdf-all">Download full set of cheat sheets</a>
	</div>
</div> -->