<h4 id-"css-foundation">The YUI CSS Foundation</h4>

<p>Note: If you are using the entire YUI CSS foundation, including <a href="../cssreset/">CSS Reset</a>, <a href="../cssfonts/">CSS Fonts</a>, and <a href="..//cssgrids/">CSS Grids</a> resources, we have provided a concatenated and minified aggregate file for you to use use. Using the single "reset-fonts-grids.css" file is better for performance than using each of the foundation files separately.</p>

<textarea name="code" class="HTML" cols="60" rows="1">
<!-- Source File -->
<link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/<?php echo($yuiCurrentVersion);?>/build/reset-fonts-grids/reset-fonts-grids.css">
</textarea>