<!--begin examples navigation-->
<div id="examples">
<?php
//TODO: REPLACE WITH REAL PATH TO EXAMPLESINFO IN TEMPLATES DIR:
//include "/Sites/yahoo/presentation/templates/examples/data/examplesInfo.php";
//echo("<h3 id='examplesList'>$component Examples:</h3>");?>
	
	<ul>
<?php
/*$currentModuleName = $section;
$aCurrentExamples = getExamplesByModule($currentModuleName, $examples);
if ($aCurrentExamples) {
	foreach($aCurrentExamples as $key=>$thisExample) {
		/*We may be including this example here because it is crosslisted
		from another component; if the linked example is in another component's
		roster, we note that parenthetically, as it will move the user
		to the other component's context.
		if ($currentModuleName != $thisExample["modules"][0]) {
			$moduleSuffix =  " (included with examples for ".$modules[$thisExample["modules"][0]]["name"].")";
		} else {
			$moduleSuffix = "";
		}
		echo "<li><a href='".$docroot.$thisExample[modules][0]."/".$key.".html'>".$thisExample["name"].$moduleSuffix."</a></li>";
		
	}
}*/
?>
	</ul>
</div>
<!--end examples navigation-->