<h5>Including Files Manually</h5>

<p>If you'd like to obtain the optimal list of files you need to manually include on your page to support this component along with any other components on your page, you can use the <a href="/yui/3/articles/hosting/#configure">YUI Dependency Configurator</a>. The Configurator uses YUI Loader to generate the optimal set of HTML script and link tags required to include the files you need for your implementation; which you can then copy/paste into your page.</p>
