	<h2 id="support">Support &amp; Community</h2>
	<p>YUIDoc is discussed in the on the <a href="http://groups.yahoo.com/group/yuidoc/">YUIDoc Community Forum</a>.</p>

	<form method="get" action="http://groups.yahoo.com/subscribe/yuidoc">
	<table cellspacing="0" cellpadding="2">
		<tr>
			<td align="right" width="50%"><input type="text" name="user" value="enter email address" size="20"></td>
			<td align="left"><input type="image" border="0" alt="Click here to join the YUIDoc Community Forum." name="Click here to join the YUIDoc Community Forum." src="http://us.i1.yimg.com/us.yimg.com/i/ydn/yuiweb/img/joinbtn.gif"></td>
		</tr>
	</table>
	</form>

    <p>In addition, please visit the <a href="http://yuiblog.com">YUIBlog</a> for updates and articles about the YUI Library written by the library's developers.</p>
	
	<h2 id="filingbugs">Filing Bugs &amp; Feature Requests</h2>
	
	<p>The YUI Library's public bug tracking and feature request repositories are located on <a href="http://sourceforge.net/projects/yui">the YUI SourceForge project site</a>.  Before filing new feature requests or bug reports, please review <a href="/yui/articles/reportingbugs/">our reporting guidelines</a>.</p>
