/* This file is auto-generated by src/loader/meta_join.py */

/**
 * YUI 3 module metadata
 * @module loader
 * @submodule yui3
 */
YUI.Env[Y.version].modules = YUI.Env[Y.version].modules || { /* METAGEN */ };
YUI.Env[Y.version].md5 = '{ /* MD5 */ }';
