var YUI_config = {
    bootstrap: false,
    combine:false,
    filter:"raw",
    allowRollup:false,
    base:"/before/"/*, 
    core:[
        "yui-base",
        "features",
        "yui-log",
        "yui-later",
        "get",
        "oop",
        "dom-base",
        "selector-native", 
        "selector-css2", 
        "event-custom-base",
        "event-base",
        "node-base", 
        "dom-style",
        "node-style",
        "event-delegate",
        "node-event-delegate",
        "dom-screen",
        "node-screen"
    ],
    loaderPath:"loader/loader.js"
    */
};
