<div id="examples" class="mod box4">
	<div class="hd">
		<h4><?php echo $component;?> Examples</h4>
	</div>
	<div class="bd">
		<ul>
			<li><a href='/yui/examples/animation/basic.html'>Basic Animation</a></li>
			<li><a href='/yui/examples/animation/easing.html'>Animation Easing</a></li>
			<li><a href='/yui/examples/animation/from.html'>Animating From a Given Value</a></li>
			<li><a href='/yui/examples/animation/units.html'>Using Custom Units for an Animation</a></li>
			<li><a href='/yui/examples/animation/attributes.html'>Animating Multiple Attributes</a></li>
			<li><a href='/yui/examples/animation/anim-chaining.html'>Chaining Animations Using <code>onComplete</code></a></li>
			<li><a href='/yui/examples/animation/colors.html'>Animating Colors</a></li>
			<li><a href='/yui/examples/animation/motion.html'>Animating Motion</a></li>
			<li><a href='/yui/examples/animation/control.html'>Animating Along a Curved Path</a></li>
			<li><a href='/yui/examples/animation/scroll.html'>Animated Scrolling</a></li>
		</ul>
	</div>
</div>
<div id="relatedexamples" class="mod box4">
	<div class="hd">
		<h4>Other YUI Examples That Make Use of the <?php echo $component;?></h4>
	</div>
	<div class="bd">
		<ul>
			<li><a href='/yui/examples/button/btn_example13.html'>Glowing Button</a> (included with examples for the <a href='../button/index.html'>Button Control</a>)</li>
			<li><a href='/yui/examples/layout/adv_layout.html'>Complex Application</a> (included with examples for the <a href='../layout/index.html'>Layout Manager (beta)</a>)</li>
		</ul>
	</div>
</div>
