<h3>AutoComplete Control Examples:</h3>

<ul>
<li><a href='/yui/examples/autocomplete/ac_states_jsarray.html'>Query a JavaScript Array for In-memory Data</a></li>
<li><a href='/yui/examples/autocomplete/ac_states_jsfunction.html'>Query a JavaScript Function for In-memory Data</a></li>
<li><a href='/yui/examples/autocomplete/ac_ysearch_json.html'>Use AutoComplete to access the Yahoo! Search JSON API</a></li>
<li><a href='/yui/examples/autocomplete/ac_ysearch_xml.html'>Use AutoComplete to access the Yahoo! Search XML API</a></li>
<li><a href='/yui/examples/autocomplete/ac_ysearch_flat.html'>Use AutoComplete to access flat-file data from a web service</a></li>
<li><a href='/yui/examples/autocomplete/ac_flickr_xml.html'>Use AutoComplete with Flickr's XML Webservice</a></li>
<li><a href='/yui/examples/autocomplete/ac_proxyless.html'>Proxyless AutoComplete pointing to the Yahoo! Search API</a></li>
<li><a href='/yui/examples/autocomplete/ac_customize.html'>Configurations Dashboard</a></li>
<li><a href='/yui/examples/autocomplete/ac_skinning.html'>Skinning Model</a></li>
</ul>




<h4 id='relatedExamples'>Other YUI Examples That Make Use of the AutoComplete Control:</h4>

<ul>
<li><a href='/yui/examples/editor/flickr_editor.html'>Flickr Image Search</a> (included with examples for the <a href='../editor/index.html'>Rich Text Editor (beta)</a>)</li>
<li><a href='/yui/examples/logger/log_autocomplete.html'>Logger Integration with YUI Components</a> (included with examples for the <a href='../logger/index.html'>Logger Control</a>)</li>
<li><a href='/yui/examples/datatable/dt_autocomplete.html'>Datatable with Autocomplete</a> (included with examples for the <a href='../datatable/index.html'>DataTable Control (beta)</a>)</li>
<li><a href='/yui/examples/layout/adv_layout.html'>Complex Application</a> (included with examples for the <a href='../layout/index.html'>Layout Manager (beta)</a>)</li>
</ul>		
