<h3>Base CSS Examples:</h3>

<ul>
<li><a href='/yui/examples/base/base-simple.html'>Basic Test Suite for YUI Base</a></li>
<li><a href='/yui/examples/base/base-in-doc.html'>YUI Base, 750px</a></li>
<li><a href='/yui/examples/base/base-in-doc2.html'>YUI Base, 950px</a></li>
<li><a href='/yui/examples/base/base-in-doc4.html'>YUI Base, 974px</a></li>
<li><a href='/yui/examples/base/base-in-doc3.html'>YUI Base, 100%</a></li>
</ul>


		
