<h3>Button Control Examples:</h3>

<ul>
<li><a href='/yui/examples/button/btn_example01.html'>Push Buttons</a></li>
<li><a href='/yui/examples/button/btn_example02.html'>Link Buttons</a></li>
<li><a href='/yui/examples/button/btn_example03.html'>Checkbox Buttons</a></li>
<li><a href='/yui/examples/button/btn_example04.html'>Radio Buttons</a></li>
<li><a href='/yui/examples/button/btn_example05.html'>Submit Buttons</a></li>
<li><a href='/yui/examples/button/btn_example06.html'>Reset Buttons</a></li>
<li><a href='/yui/examples/button/btn_example07.html'>Menu Buttons</a></li>
<li><a href='/yui/examples/button/btn_example08.html'>Split Buttons</a></li>
<li><a href='/yui/examples/button/btn_example09.html'>Calendar Menu Button</a></li>
<li><a href='/yui/examples/button/btn_example10.html'>Calendar Menu Button</a></li>
<li><a href='/yui/examples/button/btn_example11.html'>Color Picker Button</a></li>
<li><a href='/yui/examples/button/btn_example12.html'>Fixed Width Menu Button</a></li>
<li><a href='/yui/examples/button/btn_example13.html'>Glowing Button</a></li>
<li><a href='/yui/examples/button/btn_example14.html'>Slider Button</a></li>
</ul>




<h4 id='relatedExamples'>Other YUI Examples That Make Use of the Button Control:</h4>

<ul>
<li><a href='/yui/examples/datatable/dt_colshowhide.html'>Showing, Hiding, and Reordering Columns.</a> (included with examples for the <a href='../datatable/index.html'>DataTable Control (beta)</a>)</li>
<li><a href='/yui/examples/get/get-css-basic.html'>Getting CSS Style Sheets</a> (included with examples for the <a href='../get/index.html'>Get Utility</a>)</li>
<li><a href='/yui/examples/layout/adv_layout.html'>Complex Application</a> (included with examples for the <a href='../layout/index.html'>Layout Manager (beta)</a>)</li>
</ul>		
