<h3>Calendar Control Examples:</h3>

<ul>
<li><a href='/yui/examples/calendar/quickstart.html'>Quickstart Tutorial</a></li>
<li><a href='/yui/examples/calendar/multi.html'>Multi-Select Calendar</a></li>
<li><a href='/yui/examples/calendar/calgrp.html'>Multi-Page Calendar</a></li>
<li><a href='/yui/examples/calendar/minmax.html'>Minimum/Maximum Dates</a></li>
<li><a href='/yui/examples/calendar/calnavigator.html'>Calendar Navigator</a></li>
<li><a href='/yui/examples/calendar/events.html'>Handling Calendar Events</a></li>
<li><a href='/yui/examples/calendar/formtxt.html'>Calendar and Text Fields</a></li>
<li><a href='/yui/examples/calendar/formsel.html'>Calendar and Select Fields</a></li>
<li><a href='/yui/examples/calendar/render.html'>Using the Render Stack</a></li>
<li><a href='/yui/examples/calendar/popup.html'>Popup Calendar</a></li>
<li><a href='/yui/examples/calendar/germany.html'>Localization - Germany</a></li>
<li><a href='/yui/examples/calendar/japan.html'>Localization - Japan</a></li>
<li><a href='/yui/examples/calendar/calcontainer.html'>Calendar inside a Container</a></li>
<li><a href='/yui/examples/calendar/calskin.html'>Skinning The Calendar</a></li>
</ul>




<h4 id='relatedExamples'>Other YUI Examples That Make Use of the Calendar Control:</h4>

<ul>
<li><a href='/yui/examples/editor/cal_editor.html'>Calendar Plugin</a> (included with examples for the <a href='../editor/index.html'>Rich Text Editor (beta)</a>)</li>
<li><a href='/yui/examples/datatable/dt_cellediting.html'>Inline Cell Editing</a> (included with examples for the <a href='../datatable/index.html'>DataTable Control (beta)</a>)</li>
<li><a href='/yui/examples/yuiloader/yl-basic.html'>Using YUI Loader to Load the Calendar Control</a> (included with examples for the <a href='../yuiloader/index.html'>YUI Loader Utility (beta)</a>)</li>
<li><a href='/yui/examples/button/btn_example09.html'>Calendar Menu Button</a> (included with examples for the <a href='../button/index.html'>Button Control</a>)</li>
<li><a href='/yui/examples/button/btn_example10.html'>Calendar Menu Button</a> (included with examples for the <a href='../button/index.html'>Button Control</a>)</li>
<li><a href='/yui/examples/layout/calrte_layout.html'>Simple Application</a> (included with examples for the <a href='../layout/index.html'>Layout Manager (beta)</a>)</li>
<li><a href='/yui/examples/layout/adv_layout.html'>Complex Application</a> (included with examples for the <a href='../layout/index.html'>Layout Manager (beta)</a>)</li>
<li><a href='/yui/examples/profilerviewer/pv-basic.html'>Simple Profiling</a> (included with examples for the <a href='../profilerviewer/index.html'>ProfilerViewer Control (beta)</a>)</li>
</ul>		
