<h3>Charts Control (experimental) Examples:</h3>

<ul>
<li><a href='/yui/examples/charts/charts-quickstart.html'>Charts Quickstart Example</a></li>
<li><a href='/yui/examples/charts/charts-legend.html'>Chart with Legend Example</a></li>
<li><a href='/yui/examples/charts/charts-skins.html'>Skinning a Chart Example</a></li>
<li><a href='/yui/examples/charts/charts-datatable.html'>Chart and DataTable Example</a></li>
<li><a href='/yui/examples/charts/charts-xhr-polling.html'>Chart with DataSource Polling</a></li>
</ul>


		
