<h3>Color Picker Control Examples:</h3>

<ul>
<li><a href='/yui/examples/colorpicker/colorpicker-fromscript.html'>Inline Color Picker Control from Script</a></li>
<li><a href='/yui/examples/colorpicker/colorpicker-dialog-from-script.html'>Example of Color Picker Built in a Dialog via JavaScript</a></li>
<li><a href='/yui/examples/colorpicker/colorpicker-dialog-from-markup.html'>Example of Color Picker Built in a Dialog from Markup</a></li>
<li><a href='/yui/examples/colorpicker/colorpicker-custom.html'>Example of Specifying Custom Labels and Element IDs for Color Picker</a></li>
<li><a href='/yui/examples/colorpicker/colorpicker-skinning.html'>Skinning Example</a></li>
</ul>




<h4 id='relatedExamples'>Other YUI Examples That Make Use of the Color Picker Control:</h4>

<ul>
<li><a href='/yui/examples/button/btn_example11.html'>Color Picker Button</a> (included with examples for the <a href='../button/index.html'>Button Control</a>)</li>
</ul>		
