<h3>Connection Manager Examples:</h3>

<ul>
<li><a href='/yui/examples/connection/get.html'>Connection Manager GET Transaction</a></li>
<li><a href='/yui/examples/connection/post.html'>Connection Manager POST Transaction</a></li>
<li><a href='/yui/examples/connection/abort.html'>Connection Manager Transaction Timeout</a></li>
<li><a href='/yui/examples/connection/weather.html'>Retrieving a Yahoo! Weather RSS Feed</a></li>
<li><a href='/yui/examples/connection/global_customevents.html'>Subscribing to Connection Manager Global Events</a></li>
<li><a href='/yui/examples/connection/callback_customevents.html'>Subscribing to Connection Manager's Custom Events via the Callback Object</a></li>
</ul>




<h4 id='relatedExamples'>Other YUI Examples That Make Use of the Connection Manager:</h4>

<ul>
<li><a href='/yui/examples/imagecropper/conn_crop.html'>Connection Manager assisted image crop</a> (included with examples for the <a href='../imagecropper/index.html'>ImageCropper Control (beta)</a>)</li>
<li><a href='/yui/examples/treeview/dynamic_tree.html'>Dynamically Loading Node Data</a> (included with examples for the <a href='../treeview/index.html'>TreeView Control</a>)</li>
<li><a href='/yui/examples/editor/post_editor.html'>Editor Data Post with Connection Manager</a> (included with examples for the <a href='../editor/index.html'>Rich Text Editor (beta)</a>)</li>
<li><a href='/yui/examples/layout/calrte_layout.html'>Simple Application</a> (included with examples for the <a href='../layout/index.html'>Layout Manager (beta)</a>)</li>
</ul>		
