<h3>Dom Collection Examples:</h3>

<ul>
<li><a href='/yui/examples/dom/setxy.html'>Using setXY</a></li>
<li><a href='/yui/examples/dom/getxy.html'>Using getXY</a></li>
<li><a href='/yui/examples/dom/setstyle.html'>Using setStyle</a></li>
<li><a href='/yui/examples/dom/getstyle.html'>Using getStyle</a></li>
<li><a href='/yui/examples/dom/hasclass.html'>Using hasClass</a></li>
<li><a href='/yui/examples/dom/addclass.html'>Using addClass</a></li>
<li><a href='/yui/examples/dom/removeclass.html'>Using removeClass</a></li>
<li><a href='/yui/examples/dom/getelementsbyclassname.html'>Using getElementsByClassName</a></li>
</ul>


		
