<h3>Rich Text Editor (beta) Examples:</h3>

<ul>
<li><a href='/yui/examples/editor/flickr_editor.html'>Flickr Image Search</a></li>
<li><a href='/yui/examples/editor/cal_editor.html'>Calendar Plugin</a></li>
<li><a href='/yui/examples/editor/icon_editor.html'>Icon Insertion</a></li>
<li><a href='/yui/examples/editor/switch_editor.html'>Plain Text Switcher</a></li>
<li><a href='/yui/examples/editor/post_editor.html'>Editor Data Post with Connection Manager</a></li>
<li><a href='/yui/examples/editor/skinning_editor.html'>Skinning the Editor</a></li>
<li><a href='/yui/examples/editor/toolbar_editor.html'>Default Toolbar Config</a></li>
<li><a href='/yui/examples/editor/code_editor.html'>Code Editor</a></li>
<li><a href='/yui/examples/editor/tabview_editor.html'>Editor inside a Tabview Control</a></li>
<li><a href='/yui/examples/editor/multi_editor.html'>One Editor, Multiple Edit Areas</a></li>
<li><a href='/yui/examples/editor/imagebrowser_editor.html'>Editor with Custom Image Browser</a></li>
<li><a href='/yui/examples/editor/simple_editor.html'>Simple Editor &mdash; Basic Buttons</a></li>
<li><a href='/yui/examples/editor/simple_adv_editor.html'>Simple Editor &mdash; Advanced Buttons</a></li>
<li><a href='/yui/examples/editor/editor_adv_editor.html'>Editor &mdash; Basic Buttons</a></li>
<li><a href='/yui/examples/editor/autoheight_editor.html'>Editor Auto Adjusting Height</a></li>
</ul>




<h4 id='relatedExamples'>Other YUI Examples That Make Use of the Rich Text Editor (beta):</h4>

<ul>
<li><a href='/yui/examples/resize/rte_resize.html'>Custom resizing for the Rich Text Editor</a> (included with examples for the <a href='../resize/index.html'>Resize Utility (beta)</a>)</li>
<li><a href='/yui/examples/layout/calrte_layout.html'>Simple Application</a> (included with examples for the <a href='../layout/index.html'>Layout Manager (beta)</a>)</li>
<li><a href='/yui/examples/layout/adv_layout.html'>Complex Application</a> (included with examples for the <a href='../layout/index.html'>Layout Manager (beta)</a>)</li>
</ul>		
