<h3>Event Utility Examples:</h3>

<ul>
<li><a href='/yui/examples/event/eventsimple.html'>Simple Event Handling and Processing</a></li>
<li><a href='/yui/examples/event/custom-event.html'>Using Custom Events</a></li>
<li><a href='/yui/examples/event/event-timing.html'>Using onAvailable, onContentReady, and onDOMReady</a></li>
<li><a href='/yui/examples/event/event-delegation.html'>Using Event Utility and Event Delegation to Improve Performance</a></li>
</ul>




<h4 id='relatedExamples'>Other YUI Examples That Make Use of the Event Utility:</h4>

<ul>
<li><a href='/yui/examples/container/keylistener.html'>Implementing Container Keyboard Shortcuts with KeyListener</a> (included with examples for the <a href='../container/index.html'>Container Family</a>)</li>
</ul>		
