<h3>Get Utility Examples:</h3>

<ul>
<li><a href='/yui/examples/get/get-script-basic.html'>Getting a Script Node with JSON Data</a></li>
<li><a href='/yui/examples/get/get-css-basic.html'>Getting CSS Style Sheets</a></li>
</ul>




<h4 id='relatedExamples'>Other YUI Examples That Make Use of the Get Utility:</h4>

<ul>
<li><a href='/yui/examples/layout/adv_layout.html'>Complex Application</a> (included with examples for the <a href='../layout/index.html'>Layout Manager (beta)</a>)</li>
</ul>		
