<h3>Browser History Manager (beta) Examples:</h3>

<ul>
<li><a href='/yui/examples/history/history-navbar.html'>Simple Navigation Bar</a></li>
<li><a href='/yui/examples/history/history-tabview.html'>TabView Control</a></li>
<li><a href='/yui/examples/history/history-calendar.html'>Calendar Control</a></li>
<li><a href='/yui/examples/history/history-multiple.html'>Multiple Modules</a></li>
</ul>


		
