<h3>ImageCropper Control (beta) Examples:</h3>

<ul>
<li><a href='/yui/examples/imagecropper/simple_crop.html'>Simple Crop Interface</a></li>
<li><a href='/yui/examples/imagecropper/adv_crop.html'>Advanced Crop Interface</a></li>
<li><a href='/yui/examples/imagecropper/feedback_crop.html'>Real Time Crop Feedback</a></li>
<li><a href='/yui/examples/imagecropper/conn_crop.html'>Connection Manager assisted image crop</a></li>
<li><a href='/yui/examples/imagecropper/skinning_crop.html'>Skinning the ImageCropper</a></li>
</ul>


		
