<h3>Layout Manager (beta) Examples:</h3>

<ul>
<li><a href='/yui/examples/layout/page_layout.html'>Full Page Layout</a></li>
<li><a href='/yui/examples/layout/panel_layout.html'>Layout inside a resizable Panel</a></li>
<li><a href='/yui/examples/layout/grids_layout.html'>Using a Layout with Grids CSS</a></li>
<li><a href='/yui/examples/layout/nested_layout.html'>Nesting a layout</a></li>
<li><a href='/yui/examples/layout/calrte_layout.html'>Simple Application</a></li>
<li><a href='/yui/examples/layout/adv_layout.html'>Complex Application</a></li>
<li><a href='/yui/examples/layout/skinning_layout.html'>Skinning a Layout</a></li>
</ul>


		
