<h3>Logger Control Examples:</h3>

<ul>
<li><a href='/yui/examples/logger/log_basic.html'>Basic Logging</a></li>
<li><a href='/yui/examples/logger/log_reading.html'>Configuring LogReader</a></li>
<li><a href='/yui/examples/logger/log_writing.html'>Using LogWriter</a></li>
<li><a href='/yui/examples/logger/log_autocomplete.html'>Logger Integration with YUI Components</a></li>
<li><a href='/yui/examples/logger/log_skinning.html'>Skinning Model</a></li>
</ul>




<h4 id='relatedExamples'>Other YUI Examples That Make Use of the Logger Control:</h4>

<ul>
<li><a href='/yui/examples/layout/adv_layout.html'>Complex Application</a> (included with examples for the <a href='../layout/index.html'>Layout Manager (beta)</a>)</li>
</ul>		
