<h3>Menu Family Examples:</h3>

<ul>
<li><a href='/yui/examples/menu/example01.html'>Basic Menu From Markup</a></li>
<li><a href='/yui/examples/menu/example02.html'>Basic Menu From JavaScript</a></li>
<li><a href='/yui/examples/menu/example03.html'>Grouped Menu Items Using Markup</a></li>
<li><a href='/yui/examples/menu/example04.html'>Grouped Menu Items Using JavaScript</a></li>
<li><a href='/yui/examples/menu/example05.html'>Grouped Menu Items With Titles From Markup</a></li>
<li><a href='/yui/examples/menu/example06.html'>Grouped Menu Items With Titles From JavaScript</a></li>
<li><a href='/yui/examples/menu/example07.html'>Multi-tiered Menu From Markup</a></li>
<li><a href='/yui/examples/menu/example08.html'>Multi-tiered Menu From JavaScript</a></li>
<li><a href='/yui/examples/menu/example09.html'>Handling Menu Click Events</a></li>
<li><a href='/yui/examples/menu/example10.html'>Listening For Menu Events</a></li>
<li><a href='/yui/examples/menu/example11.html'>MenuItem Configuration Properties</a></li>
<li><a href='/yui/examples/menu/example12.html'>Setting Menu Configuration Properties At Runtime</a></li>
<li><a href='/yui/examples/menu/leftnavfrommarkup.html'>Website Left Nav With Submenus Built From Markup</a></li>
<li><a href='/yui/examples/menu/leftnavfromjs.html'>Website Left Nav With Submenus From JavaScript</a></li>
<li><a href='/yui/examples/menu/topnavfrommarkup.html'>Website Top Nav With Submenus Built From Markup</a></li>
<li><a href='/yui/examples/menu/topnavfromjs.html'>Website Top Nav With Submenus From JavaScript</a></li>
<li><a href='/yui/examples/menu/leftnavfrommarkupwithanim.html'>Website Left Nav Using Animation With Submenus Built From Markup</a></li>
<li><a href='/yui/examples/menu/leftnavfromjswithanim.html'>Website Left Nav Using Animation With Submenus From JavaScript</a></li>
<li><a href='/yui/examples/menu/topnavfrommarkupwithanim.html'>Website Top Nav Using Animation With Submenus Built From Markup</a></li>
<li><a href='/yui/examples/menu/topnavfromjswithanim.html'>Website Top Nav Using Animation With Submenus From JavaScript</a></li>
<li><a href='/yui/examples/menu/contextmenu.html'>Context Menu</a></li>
<li><a href='/yui/examples/menu/tablecontextmenu.html'>Adding A Context Menu To A Table</a></li>
<li><a href='/yui/examples/menu/treeviewcontextmenu.html'>Adding A Context Menu To A TreeView</a></li>
<li><a href='/yui/examples/menu/programsmenu.html'>OS-Style Programs Menu</a></li>
<li><a href='/yui/examples/menu/applicationmenubar.html'>Application Menubar</a></li>
<li><a href='/yui/examples/menu/menuwaiaria.html'>Implementing ARIA Roles and States with Menu</a></li>
</ul>




<h4 id='relatedExamples'>Other YUI Examples That Make Use of the Menu Family:</h4>

<ul>
<li><a href='/yui/examples/datatable/dt_contextmenu.html'>Context Menu Integration</a> (included with examples for the <a href='../datatable/index.html'>DataTable Control (beta)</a>)</li>
<li><a href='/yui/examples/button/btn_example07.html'>Menu Buttons</a> (included with examples for the <a href='../button/index.html'>Button Control</a>)</li>
<li><a href='/yui/examples/button/btn_example08.html'>Split Buttons</a> (included with examples for the <a href='../button/index.html'>Button Control</a>)</li>
<li><a href='/yui/examples/button/btn_example11.html'>Color Picker Button</a> (included with examples for the <a href='../button/index.html'>Button Control</a>)</li>
<li><a href='/yui/examples/button/btn_example12.html'>Fixed Width Menu Button</a> (included with examples for the <a href='../button/index.html'>Button Control</a>)</li>
<li><a href='/yui/examples/button/btn_example14.html'>Slider Button</a> (included with examples for the <a href='../button/index.html'>Button Control</a>)</li>
<li><a href='/yui/examples/profilerviewer/pv-api.html'>Using the ProfilerViewer API while Profiling the YUI Menu Control</a> (included with examples for the <a href='../profilerviewer/index.html'>ProfilerViewer Control (beta)</a>)</li>
</ul>		
