<h3>ProfilerViewer Control (beta) Examples:</h3>

<ul>
<li><a href='/yui/examples/profilerviewer/pv-basic.html'>Simple Profiling</a></li>
<li><a href='/yui/examples/profilerviewer/pv-api.html'>Using the ProfilerViewer API while Profiling the YUI Menu Control</a></li>
<li><a href='/yui/examples/profilerviewer/pv-bootstrap.html'>Using Profiler and ProfilerViewer to Profile non-YUI Code</a></li>
<li><a href='/yui/examples/profilerviewer/pv-skin.html'>Skinning the ProfilerViewer Control</a></li>
<li><a href='/yui/examples/profilerviewer/pv-spanish.html'>ProfilerViewer Internationalization: Spanish</a></li>
<li><a href='/yui/examples/profilerviewer/pv-german.html'>ProfilerViewer Internationalization: German</a></li>
</ul>


		
