<h3>Resize Utility (beta) Examples:</h3>

<ul>
<li><a href='/yui/examples/resize/simple_resize.html'>Simple Resize</a></li>
<li><a href='/yui/examples/resize/proxy_resize.html'>Proxy Resize</a></li>
<li><a href='/yui/examples/resize/anim_resize.html'>Animated Proxy Resize</a></li>
<li><a href='/yui/examples/resize/eightway_resize.html'>8-way Element Resize</a></li>
<li><a href='/yui/examples/resize/ghost_resize.html'>Ghosting and Custom Proxy Resize</a></li>
<li><a href='/yui/examples/resize/rte_resize.html'>Custom resizing for the Rich Text Editor</a></li>
<li><a href='/yui/examples/resize/grids_resize.html'>Split Pane resizing with Grids CSS</a></li>
<li><a href='/yui/examples/resize/skinning_resize.html'>Skinning the Resize Utility</a></li>
</ul>




<h4 id='relatedExamples'>Other YUI Examples That Make Use of the Resize Utility (beta):</h4>

<ul>
<li><a href='/yui/examples/layout/panel_layout.html'>Layout inside a resizable Panel</a> (included with examples for the <a href='../layout/index.html'>Layout Manager (beta)</a>)</li>
<li><a href='/yui/examples/container/panel-resize.html'>Creating a Resizable Panel</a> (included with examples for the <a href='../container/index.html'>Container Family</a>)</li>
<li><a href='/yui/examples/layout/adv_layout.html'>Complex Application</a> (included with examples for the <a href='../layout/index.html'>Layout Manager (beta)</a>)</li>
</ul>		
