<h3>Slider Control Examples:</h3>

<ul>
<li><a href='/yui/examples/slider/slider-simple.html'>Basic Vertical Slider</a></li>
<li><a href='/yui/examples/slider/slider-ticks.html'>Horizontal Slider with Tick Marks</a></li>
<li><a href='/yui/examples/slider/slider-rgb.html'>RBG Slider Control</a></li>
<li><a href='/yui/examples/slider/slider_vert_swapped.html'>Bottom to top Vertical Slider</a></li>
<li><a href='/yui/examples/slider/slider_dual_thumb.html'>Horizontal Slider with two thumbs</a></li>
<li><a href='/yui/examples/slider/slider_dual_with_highlight.html'>Dual-thumb Slider with range highlight</a></li>
</ul>




<h4 id='relatedExamples'>Other YUI Examples That Make Use of the Slider Control:</h4>

<ul>
<li><a href='/yui/examples/button/btn_example14.html'>Slider Button</a> (included with examples for the <a href='../button/index.html'>Button Control</a>)</li>
<li><a href='/yui/examples/layout/adv_layout.html'>Complex Application</a> (included with examples for the <a href='../layout/index.html'>Layout Manager (beta)</a>)</li>
</ul>		
