<h3>YAHOO Global Object Examples:</h3>

<ul>
<li><a href='/yui/examples/yahoo/yahoo_type_checking.html'>Type-Checking Your Data</a></li>
<li><a href='/yui/examples/yahoo/yahoo_ua_detection.html'>User Agent Detection</a></li>
<li><a href='/yui/examples/yahoo/yahoo_extend.html'>Creating Class Hierarchies with <code>YAHOO.lang.extend</code></a></li>
<li><a href='/yui/examples/yahoo/yahoo_augment_proto.html'>Creating a Composition-Based Class Structure Using <code>YAHOO.lang.augmentProto</code></a></li>
<li><a href='/yui/examples/yahoo/yahoo_augment_object.html'>Add Behavior to Objects or Static Classes with <code>YAHOO.lang.augmentObject</code></a></li>
<li><a href='/yui/examples/yahoo/yahoo_merge.html'>Combining Simple Data Sets with <code>YAHOO.lang.merge</code></a></li>
</ul>


		
