<h3>YUI Loader Utility (beta) Examples:</h3>

<ul>
<li><a href='/yui/examples/yuiloader/yl-basic.html'>Using YUI Loader to Load the Calendar Control</a></li>
<li><a href='/yui/examples/yuiloader/yl-insert.html'>Using YUI Loader to Place Additional Components on a Page</a></li>
<li><a href='/yui/examples/yuiloader/yl-addmodule.html'>Using addModule to Add Custom (Non-YUI) Content with YUILoader</a></li>
<li><a href='/yui/examples/yuiloader/yl-list.html'>Use YUILoader to list requirements for a set of components.</a></li>
</ul>




<h4 id='relatedExamples'>Other YUI Examples That Make Use of the YUI Loader Utility (beta):</h4>

<ul>
<li><a href='/yui/examples/layout/adv_layout.html'>Complex Application</a> (included with examples for the <a href='../layout/index.html'>Layout Manager (beta)</a>)</li>
</ul>		
